4.1 Exercise on Functions:
Task - 1

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
def convert_units():
    """
    Converts between different units: length, weight, and volume.
    """
    try:
        print("Choose conversion type:")
        print("1. Length (m <-> ft)")
        print("2. Weight (kg <-> lbs)")
        print("3. Volume (L <-> gal)")

        choice = int(input("Enter choice (1-3): "))

        if choice == 1:
            print("1. Meters to Feet\n2. Feet to Meters")
            sub_choice = int(input("Enter choice (1 or 2): "))
            value = float(input("Enter value: "))

            if sub_choice == 1:
                print(f"{value} meters = {value * 3.28084:.2f} feet")
            elif sub_choice == 2:
                print(f"{value} feet = {value / 3.28084:.2f} meters")
            else:
                print("Invalid choice.")

        elif choice == 2:
            print("1. Kilograms to Pounds\n2. Pounds to Kilograms")
            sub_choice = int(input("Enter choice (1 or 2): "))
            value = float(input("Enter value: "))

            if sub_choice == 1:
                print(f"{value} kg = {value * 2.20462:.2f} lbs")
            elif sub_choice == 2:
                print(f"{value} lbs = {value / 2.20462:.2f} kg")
            else:
                print("Invalid choice.")

        elif choice == 3:
            print("1. Liters to Gallons\n2. Gallons to Liters")
            sub_choice = int(input("Enter choice (1 or 2): "))
            value = float(input("Enter value: "))

            if sub_choice == 1:
                print(f"{value} L = {value * 0.264172:.2f} gal")
            elif sub_choice == 2:
                print(f"{value} gal = {value / 0.264172:.2f} L")
            else:
                print("Invalid choice.")

        else:
            print("Invalid choice.")

    except ValueError:
        print("Invalid input.")

convert_units()

Choose conversion type:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Enter choice (1-3): 2
1. Kilograms to Pounds
2. Pounds to Kilograms
Enter choice (1 or 2): 1
Enter value: 10
10.0 kg = 22.05 lbs


Task - 2:

In [ ]:
def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    return max(numbers)

def find_minimum(numbers):
    return min(numbers)

def main():
    try:
        print("\nSelect an operation:")
        print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")

        choice = int(input("Enter choice (1-4): "))
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            print("List cannot be empty.")
            return

        if choice == 1:
            print("Sum:", calculate_sum(numbers))
        elif choice == 2:
            print("Average:", calculate_average(numbers))
        elif choice == 3:
            print("Maximum:", find_maximum(numbers))
        elif choice == 4:
            print("Minimum:", find_minimum(numbers))
        else:
            print("Invalid choice.")

    except ValueError:
        print("Invalid input.")

main()


Select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1-4): 4
Enter numbers separated by spaces: 1 3 5 6 7 8
Minimum: 1.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:

In [ ]:
def extract_every_other(lst):
    return lst[::2]


print(extract_every_other([9, 8, 10, 5, 6]))

[9, 10, 6]


2. Slice a Sublist:

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]


print(get_sublist([3, 4, 6, 7, 8, 9], 2, 4))

[6, 7, 8]


Task 3: Reverse a List Using Slicing

In [ ]:
def reverse_list(lst):
    return lst[::-1]


print(reverse_list([6, 8, 4, 7, 10]))

[10, 7, 4, 8, 6]


Task 4: Remove First and Last Elements

In [ ]:
def remove_first_last(lst):
    return lst[1:-1] if len(lst) > 2 else []

# Example
print(remove_first_last([6, 5, 10, 4, 7]))

[5, 10, 4]


5. Get the First n Elements:

In [ ]:
def get_first_n(lst, n):
    return lst[:n]

# Example
print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


6. Extract Elements from the End:

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([8, 9, 10, 4, 5], 2))

[4, 5]


7. Extract Elements in Reverse Order:

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example
print(reverse_skip([8, 11, 12, 34, 45, 43]))

[45, 12, 8]


4.3 Exercise on Nested List:
1. Flatten a Nested List:

In [ ]:
def flatten(lst):
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(flatten(sublist))
        else:
            flat_list.append(sublist)
    return flat_list


print(flatten([[11, 8], [6, 9], [5]]))

[11, 8, 6, 9, 5]


2. Accessing Nested List Elements:

In [ ]:
def access_nested_element(lst, indices):
    """Retrieves an element from a nested list given a list of indices."""
    for index in indices:
        lst = lst[index]  # Navigate through the nested structure
    return lst


nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(nested_list, [1, 2]))

6


3. Sum of All Elements in a Nested List:

In [ ]:
def sum_nested(lst):
    """Calculates the sum of all elements in a nested list."""
    return sum(sum_nested(sublist) if isinstance(sublist, list) else sublist for sublist in lst)


print(sum_nested([[1, 21], [9, [4, 6]], 7]))

48


4. Remove Specific Element from a Nested List:

In [ ]:
def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    return [remove_element(sublist, elem) if isinstance(sublist, list) else sublist
            for sublist in lst if sublist != elem]

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

In [ ]:
def find_max(lst):
    """Finds the maximum value in a nested list."""
    return max(find_max(sublist) if isinstance(sublist, list) else sublist for sublist in lst)

print(find_max([[1, 11], [9, [7, 5]], 6]))

11


6. Count Occurrences of an Element in a Nested List:

In [ ]:
def count_occurrences(lst, elem):
    """Counts the occurrences of a specific element in a nested list."""
    return sum(count_occurrences(sublist, elem) if isinstance(sublist, list) else (sublist == elem)
               for sublist in lst)


print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

3


7. Flatten a List of Lists of Lists:

In [ ]:
def deep_flatten(lst):
    """Flattens a deeply nested list into a single list, regardless of depth."""
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(deep_flatten(sublist))  # Recursively flatten all levels
        else:
            flat_list.append(sublist)
    return flat_list

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

In [ ]:
def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = flatten(lst)  # Reusing the flatten function
    return sum(flat_list) / len(flat_list) if flat_list else 0  # Avoid division by zero

print(average_nested([[1, 3], [3, 6], [10, 6]]))

4.833333333333333


10 To - Do - NumPy
10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [ ]:
import numpy as np

In [ ]:
import numpy as np

#Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

#Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll One Array:\n", ones_array)

#Return a new array of given shape and type, filled with a specified fill value
filled_array = np.full((3, 3), 7)  # 3x3 array filled with value 7
print("\nArray filled with a specific value:\n", filled_array)

#Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])  # Example given array
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Array with Same Shape as Given Array:\n", zeros_like_array)

#Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes Array with Same Shape as Given Array:\n", ones_like_array)

#Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)

Empty Array:
 [[2.91092046e-316 0.00000000e+000]
 [1.95334101e+184 6.53579294e-310]]

All One Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with a specific value:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Array with Same Shape as Given Array:
 [[0 0 0]
 [0 0 0]]

Ones Array with Same Shape as Given Array:
 [[1 1 1]
 [1 1 1]]

Converted NumPy Array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:

#Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:\n", arr1)

#Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", arr2)

#Create a 3x3 identity matrix
arr3 = np.eye(3)
print("\n3x3 Identity Matrix:\n", arr3)

#Create a random array of size 30 and find the mean
arr4 = np.random.random(30)  # Random values between 0 and 1
mean_val = arr4.mean()
print("\nMean of Random 30-Element Array:\n", mean_val)

#Create a 10x10 array with random values and find min & max
arr5 = np.random.random((10, 10))
min_val= arr5.min()
max_val = arr5.max()
print("\nMin and Max in 10x10 Random Array:\n", min_val, max_val)

#Create a zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1  # 5th element (index 4) set to 1
print("\nZero Array with 5th Element as 1:\n", arr6)

#Reverse an array arr = [1,2,0,0,4,0]
arr7 = np.array([1, 2, 0, 0, 4, 0])[::-1]
print("\nReversed Array:\n", arr7)

#Create a 2D array with 1 on border and 0 inside
arr8 = np.ones((5, 5))  # Create an all-ones array
arr8[1:-1, 1:-1] = 0  # Set inside elements to 0
print("\n2D Array with Border 1 and Inside 0:\n", arr8)

#Create an 8x8 matrix and fill it with a checkerboard pattern
arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1  # Fill alternate rows
arr9[::2, 1::2] = 1  # Fill alternate columns
print("\n8x8 Checkerboard Pattern:\n", arr9)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean of Random 30-Element Array:
 0.4090953608051875

Min and Max in 10x10 Random Array:
 0.007933060262682035 0.994726496483534

Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed Array:
 [0 4 0 0 2 1]

2D Array with Border 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

In [ ]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

#Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

#Multiply the array with an integer (choosing 3)
mul_x = x * 3
print("\nMultiplication of x with 3:\n", mul_x)

#Find the square of each element of x
square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)

#Find the dot product
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y

print("\nDot product of v and w:", dot_vw)
print("\nDot product of x and v:\n", dot_xv)
print("\nDot product of x and y:\n", dot_xy)

#Concatenate x and y along rows
concat_xy_row = np.concatenate((x, y), axis=0)
print("\nConcatenation of x and y along rows:\n", concat_xy_row)

#Concatenate v and w along columns
concat_vw_col = np.column_stack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_vw_col)

#Concatenate x and v (Observe Error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError when concatenating x and v:", e)

Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]

Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

1.Prove A * A⁻¹ = I

In [ ]:
# Define matrices
A = np.array([[3, 4], [7, 8]])
# Compute inverse of A
A_inv = np.linalg.inv(A)
# Multiply A with its inverse
I = np.dot(A, A_inv)
print("A * A⁻¹ = Identity matrix\n", I)

A * A⁻¹ = Identity matrix
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ≠ BA

In [ ]:
# Define another matrix B
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("\nBA:\n", BA)

# Check if AB is equal to BA
equal = np.array_equal(AB, BA)
print("AB = BA :", equal)

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]
AB = BA : False


3. Prove (AB)^T = B^T * A^T

In [ ]:
# Compute (AB)^T
AB_T = np.transpose(AB)

# Compute B^T and A^T, then multiply
BT = np.transpose(B)
AT = np.transpose(A)
BT_AT = np.dot(BT, AT)

# Check if both are equal
equal_transpose = np.array_equal(AB_T, BT_AT)

print("\n(AB)^T:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)
print("(AB)^T = B^T * A^T:", equal_transpose)


(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]
(AB)^T = B^T * A^T: True


• Solve the following system of Linear equation using Inverse Methods.
2x−3y + z =−1
x−y + 2z =−3
3x + y−z = 9

In [ ]:
# Define matrices
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

# Compute inverse of A
A_inv_matrix = np.linalg.inv(A_matrix)

# Solve for X
X_solution = np.dot(A_inv_matrix, B_matrix)

print("Solution for (x, y, z):\n", X_solution)

Solution for (x, y, z):
 [ 2.  1. -2.]


solve the above equation using np.linalg.inv function.

In [ ]:
# Solve AX = B directly
X_solve = np.linalg.solve(A_matrix, B_matrix)

print("Solution using np.linalg.solve():\n", X_solve)

Solution using np.linalg.solve():
 [ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:

In [ ]:
import time

In [ ]:
# Define size parameters
size = 1_000_000  # 1 million elements
matrix_size = 1000  # 1000x1000 matrix
# Generate random data for lists and arrays
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
array1 = np.arange(size)
array2 = np.arange(size)
# 1. Element-wise Addition
# Using Python lists
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
list_add_time = time.time() - start_time
# Using NumPy arrays
start_time = time.time()
array_addition = array1 + array2
array_add_time = time.time() - start_time
print(f"Element-wise Addition - Python List Time: {list_add_time:.6f} sec")
print(f"Element-wise Addition - NumPy Array Time: {array_add_time:.6f} sec\n")

Element-wise Addition - Python List Time: 0.086572 sec
Element-wise Addition - NumPy Array Time: 0.005435 sec



2. Element-wise Multiplication

In [ ]:
# Using Python lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
list_mult_time = time.time() - start_time
# Using NumPy arrays
start_time = time.time()
array_multiplication = array1 * array2
array_mult_time = time.time() - start_time
print(f"Element-wise Multiplication - Python List Time: {list_mult_time:.6f} sec")
print(f"Element-wise Multiplication - NumPy Array Time: {array_mult_time:.6f} sec\n")

Element-wise Multiplication - Python List Time: 0.086338 sec
Element-wise Multiplication - NumPy Array Time: 0.004225 sec



3. Dot Product

In [ ]:
# Using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
list_dot_time = time.time() - start_time
# Using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
array_dot_time = time.time() - start_time
print(f"Dot Product - Python List Time: {list_dot_time:.6f} sec")
print(f"Dot Product - NumPy Array Time: {array_dot_time:.6f} sec\n")

Dot Product - Python List Time: 0.101308 sec
Dot Product - NumPy Array Time: 0.001970 sec



4. Matrix Multiplication

In [ ]:
# Generate random 1000x1000 matrices for NumPy
array_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
array_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
# Using NumPy arrays
start_time = time.time()
array_matrix_result = np.dot(array_matrix1, array_matrix2)
array_matrix_time = time.time() - start_time
print(f"Matrix Multiplication (1000x1000) - NumPy Array Time: {array_matrix_time:.6f} sec")
print("Matrix Multiplication using Python Lists skipped due to slow execution.")

Matrix Multiplication (1000x1000) - NumPy Array Time: 1.705875 sec
Matrix Multiplication using Python Lists skipped due to slow execution.


NumPy is much faster than Python lists in all operations, especially for element-wise calculations and dot products, thanks to its optimized vectorized operations. The biggest difference is in matrix multiplication—NumPy handles it quickly, while Python lists take a lot more time due to inefficient looping. Overall, NumPy is the better choice for handling large datasets and numerical tasks efficiently.